export const GUEST_LOGIN = 'GUEST_LOGIN';
export const SET_TEAM = 'SET_TEAM';
export const UPDATE_PICKS = 'UPDATE_PICKS';
export const CREATE_STANDINGS_DATA = 'CREATE_STANDINGS_DATA';
export const GUEST_PICKS_IN_STANDINGS = 'GUEST_PICKS_IN_STANDINGS';
export const AUTOPICK_GUEST = 'AUTOPICK_GUEST';
export const CHANGE_MATCHDAY = 'CHANGE_MATCHDAY';
export const GUEST_LOGOUT = 'GUEST_LOGOUT';